# Generated by Django 4.2.16 on 2025-02-24 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del solicitante')),
                ('proyecto', models.TextField(verbose_name='Descripción del proyecto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('dependencia_solicita', models.CharField(max_length=100)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('responsable_dependencia', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='solicitudes_pdf/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cuenta_con_internet', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='¿Cuentan con Internet?')),
            ],
        ),
    ]
